/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductionEntry = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
  'operationId' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const StockTransaction = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'total' : IDL.Float64,
  'transactionType' : IDL.Text,
  'date' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'quantity' : IDL.Nat,
  'transactedBy' : IDL.Text,
  'remainingQuantity' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'ifscCode' : IDL.Text,
  'name' : IDL.Text,
  'joiningDate' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'mobile' : IDL.Text,
  'workerType' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'currentQuantity' : IDL.Nat,
  'itemType' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Operation = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'ratePerPiece' : IDL.Float64,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'todayAttendancePresent' : IDL.Nat,
  'activeEmployees' : IDL.Nat,
  'todayProductionTotal' : IDL.Float64,
  'currentMonthProductionTotal' : IDL.Float64,
});
export const Counts = IDL.Record({
  'attendances' : IDL.Nat,
  'employees' : IDL.Nat,
  'inventoryItems' : IDL.Nat,
  'productions' : IDL.Nat,
  'operations' : IDL.Nat,
  'stockTransactions' : IDL.Nat,
});
export const InventoryStats = IDL.Record({
  'totalStockAdded' : IDL.Nat,
  'totalValue' : IDL.Float64,
  'totalStockRemoved' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const SalaryRecord = IDL.Record({
  'salary' : IDL.Float64,
  'employeeName' : IDL.Text,
  'ifscCode' : IDL.Text,
  'productionAmount' : IDL.Float64,
  'bankName' : IDL.Text,
  'attendanceCount' : IDL.Nat,
  'employeeId' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProductionEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(ProductionEntry)],
      [],
    ),
  'addStockTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(StockTransaction)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllAttendance' : IDL.Func([], [], []),
  'clearAllEmployees' : IDL.Func([], [], []),
  'clearAllInventory' : IDL.Func([], [], []),
  'clearAllOperations' : IDL.Func([], [], []),
  'clearAllProduction' : IDL.Func([], [], []),
  'clearAttendanceByMonth' : IDL.Func([IDL.Text], [], []),
  'clearInventoryTransactions' : IDL.Func([], [], []),
  'clearProductionByMonth' : IDL.Func([IDL.Text], [], []),
  'createEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Employee],
      [],
    ),
  'createInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [InventoryItem],
      [],
    ),
  'createOperation' : IDL.Func([IDL.Text, IDL.Float64], [Operation], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteOperation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceByEmployeeMonth' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDataCounts' : IDL.Func([], [Counts], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getInventoryStats' : IDL.Func([], [InventoryStats], ['query']),
  'getMonthlySalarySheet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
  'getProductionByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getProductionByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getProductionByEmployeeMonth' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getProductionByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getStockTransactionsByItem' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Attendance], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
  'searchOperations' : IDL.Func([IDL.Text], [IDL.Vec(Operation)], ['query']),
  'startsWith' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'updateEmployee' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Opt(Employee)],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Opt(InventoryItem)],
      [],
    ),
  'updateOperation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Opt(Operation)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductionEntry = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
    'operationId' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const StockTransaction = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'total' : IDL.Float64,
    'transactionType' : IDL.Text,
    'date' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'quantity' : IDL.Nat,
    'transactedBy' : IDL.Text,
    'remainingQuantity' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'ifscCode' : IDL.Text,
    'name' : IDL.Text,
    'joiningDate' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'mobile' : IDL.Text,
    'workerType' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'currentQuantity' : IDL.Nat,
    'itemType' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Operation = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'ratePerPiece' : IDL.Float64,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'todayAttendancePresent' : IDL.Nat,
    'activeEmployees' : IDL.Nat,
    'todayProductionTotal' : IDL.Float64,
    'currentMonthProductionTotal' : IDL.Float64,
  });
  const Counts = IDL.Record({
    'attendances' : IDL.Nat,
    'employees' : IDL.Nat,
    'inventoryItems' : IDL.Nat,
    'productions' : IDL.Nat,
    'operations' : IDL.Nat,
    'stockTransactions' : IDL.Nat,
  });
  const InventoryStats = IDL.Record({
    'totalStockAdded' : IDL.Nat,
    'totalValue' : IDL.Float64,
    'totalStockRemoved' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const SalaryRecord = IDL.Record({
    'salary' : IDL.Float64,
    'employeeName' : IDL.Text,
    'ifscCode' : IDL.Text,
    'productionAmount' : IDL.Float64,
    'bankName' : IDL.Text,
    'attendanceCount' : IDL.Nat,
    'employeeId' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProductionEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(ProductionEntry)],
        [],
      ),
    'addStockTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(StockTransaction)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllAttendance' : IDL.Func([], [], []),
    'clearAllEmployees' : IDL.Func([], [], []),
    'clearAllInventory' : IDL.Func([], [], []),
    'clearAllOperations' : IDL.Func([], [], []),
    'clearAllProduction' : IDL.Func([], [], []),
    'clearAttendanceByMonth' : IDL.Func([IDL.Text], [], []),
    'clearInventoryTransactions' : IDL.Func([], [], []),
    'clearProductionByMonth' : IDL.Func([IDL.Text], [], []),
    'createEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Employee],
        [],
      ),
    'createInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [InventoryItem],
        [],
      ),
    'createOperation' : IDL.Func([IDL.Text, IDL.Float64], [Operation], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteOperation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByEmployeeMonth' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDataCounts' : IDL.Func([], [Counts], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getInventoryStats' : IDL.Func([], [InventoryStats], ['query']),
    'getMonthlySalarySheet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getOperation' : IDL.Func([IDL.Text], [IDL.Opt(Operation)], ['query']),
    'getProductionByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionByEmployeeMonth' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getProductionByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getStockTransactionsByItem' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listOperations' : IDL.Func([], [IDL.Vec(Operation)], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Attendance],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
    'searchOperations' : IDL.Func([IDL.Text], [IDL.Vec(Operation)], ['query']),
    'startsWith' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'updateEmployee' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(Employee)],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Opt(InventoryItem)],
        [],
      ),
    'updateOperation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Opt(Operation)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };