/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : string,
  'date' : string,
  'employeeId' : string,
}
export interface Counts {
  'attendances' : bigint,
  'employees' : bigint,
  'inventoryItems' : bigint,
  'productions' : bigint,
  'operations' : bigint,
  'stockTransactions' : bigint,
}
export interface DashboardStats {
  'totalEmployees' : bigint,
  'todayAttendancePresent' : bigint,
  'activeEmployees' : bigint,
  'todayProductionTotal' : number,
  'currentMonthProductionTotal' : number,
}
export interface Employee {
  'id' : string,
  'status' : string,
  'ifscCode' : string,
  'name' : string,
  'joiningDate' : string,
  'bankName' : string,
  'accountNumber' : string,
  'mobile' : string,
  'workerType' : string,
}
export interface InventoryItem {
  'id' : string,
  'name' : string,
  'unit' : string,
  'pricePerUnit' : number,
  'currentQuantity' : bigint,
  'itemType' : string,
  'quantity' : bigint,
}
export interface InventoryStats {
  'totalStockAdded' : bigint,
  'totalValue' : number,
  'totalStockRemoved' : bigint,
  'totalItems' : bigint,
  'totalQuantity' : bigint,
}
export interface Operation {
  'id' : string,
  'name' : string,
  'ratePerPiece' : number,
}
export interface ProductionEntry {
  'id' : string,
  'date' : string,
  'employeeId' : string,
  'operationId' : string,
  'quantity' : bigint,
  'amount' : number,
}
export interface SalaryRecord {
  'salary' : number,
  'employeeName' : string,
  'ifscCode' : string,
  'productionAmount' : number,
  'bankName' : string,
  'attendanceCount' : bigint,
  'employeeId' : string,
  'accountNumber' : string,
}
export interface StockTransaction {
  'id' : string,
  'itemId' : string,
  'total' : number,
  'transactionType' : string,
  'date' : string,
  'pricePerUnit' : number,
  'quantity' : bigint,
  'transactedBy' : string,
  'remainingQuantity' : bigint,
  'remarks' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProductionEntry' : ActorMethod<
    [string, string, string, bigint],
    [] | [ProductionEntry]
  >,
  'addStockTransaction' : ActorMethod<
    [string, string, bigint, number, string, string, string],
    [] | [StockTransaction]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllAttendance' : ActorMethod<[], undefined>,
  'clearAllEmployees' : ActorMethod<[], undefined>,
  'clearAllInventory' : ActorMethod<[], undefined>,
  'clearAllOperations' : ActorMethod<[], undefined>,
  'clearAllProduction' : ActorMethod<[], undefined>,
  'clearAttendanceByMonth' : ActorMethod<[string], undefined>,
  'clearInventoryTransactions' : ActorMethod<[], undefined>,
  'clearProductionByMonth' : ActorMethod<[string], undefined>,
  'createEmployee' : ActorMethod<
    [string, string, string, string, string, string, string],
    Employee
  >,
  'createInventoryItem' : ActorMethod<
    [string, bigint, string, string, number],
    InventoryItem
  >,
  'createOperation' : ActorMethod<[string, number], Operation>,
  'deleteEmployee' : ActorMethod<[string], boolean>,
  'deleteInventoryItem' : ActorMethod<[string], boolean>,
  'deleteOperation' : ActorMethod<[string], boolean>,
  'getAttendanceByDate' : ActorMethod<[string], Array<Attendance>>,
  'getAttendanceByEmployeeMonth' : ActorMethod<
    [string, string],
    Array<Attendance>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDataCounts' : ActorMethod<[], Counts>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getInventoryStats' : ActorMethod<[], InventoryStats>,
  'getMonthlySalarySheet' : ActorMethod<[string], Array<SalaryRecord>>,
  'getOperation' : ActorMethod<[string], [] | [Operation]>,
  'getProductionByDate' : ActorMethod<[string], Array<ProductionEntry>>,
  'getProductionByEmployee' : ActorMethod<[string], Array<ProductionEntry>>,
  'getProductionByEmployeeMonth' : ActorMethod<
    [string, string],
    Array<ProductionEntry>
  >,
  'getProductionByMonth' : ActorMethod<[string], Array<ProductionEntry>>,
  'getStockTransactionsByItem' : ActorMethod<[string], Array<StockTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEmployees' : ActorMethod<[], Array<Employee>>,
  'listInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'listOperations' : ActorMethod<[], Array<Operation>>,
  'markAttendance' : ActorMethod<[string, string, string], Attendance>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEmployees' : ActorMethod<[string], Array<Employee>>,
  'searchOperations' : ActorMethod<[string], Array<Operation>>,
  'startsWith' : ActorMethod<[string, string], boolean>,
  'updateEmployee' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    [] | [Employee]
  >,
  'updateInventoryItem' : ActorMethod<
    [string, string, bigint, string, string, bigint, number],
    [] | [InventoryItem]
  >,
  'updateOperation' : ActorMethod<[string, string, number], [] | [Operation]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];