/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Operation {
    id: string;
    name: string;
    ratePerPiece: number;
}
export interface SalaryRecord {
    salary: number;
    employeeName: string;
    ifscCode: string;
    productionAmount: number;
    bankName: string;
    attendanceCount: bigint;
    employeeId: string;
    accountNumber: string;
}
export interface ProductionEntry {
    id: string;
    date: string;
    employeeId: string;
    operationId: string;
    quantity: bigint;
    amount: number;
}
export interface InventoryItem {
    id: string;
    name: string;
    unit: string;
    pricePerUnit: number;
    currentQuantity: bigint;
    itemType: string;
    quantity: bigint;
}
export interface Counts {
    attendances: bigint;
    employees: bigint;
    inventoryItems: bigint;
    productions: bigint;
    operations: bigint;
    stockTransactions: bigint;
}
export interface Attendance {
    id: string;
    status: string;
    date: string;
    employeeId: string;
}
export interface Employee {
    id: string;
    status: string;
    ifscCode: string;
    name: string;
    joiningDate: string;
    bankName: string;
    accountNumber: string;
    mobile: string;
    workerType: string;
}
export interface StockTransaction {
    id: string;
    itemId: string;
    total: number;
    transactionType: string;
    date: string;
    pricePerUnit: number;
    quantity: bigint;
    transactedBy: string;
    remainingQuantity: bigint;
    remarks: string;
}
export interface InventoryStats {
    totalStockAdded: bigint;
    totalValue: number;
    totalStockRemoved: bigint;
    totalItems: bigint;
    totalQuantity: bigint;
}
export interface UserProfile {
    name: string;
}
export interface DashboardStats {
    totalEmployees: bigint;
    todayAttendancePresent: bigint;
    activeEmployees: bigint;
    todayProductionTotal: number;
    currentMonthProductionTotal: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProductionEntry(date: string, employeeId: string, operationId: string, quantity: bigint): Promise<ProductionEntry | null>;
    addStockTransaction(itemId: string, transactionType: string, quantity: bigint, pricePerUnit: number, transactedBy: string, remarks: string, date: string): Promise<StockTransaction | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearAllAttendance(): Promise<void>;
    clearAllEmployees(): Promise<void>;
    clearAllInventory(): Promise<void>;
    clearAllOperations(): Promise<void>;
    clearAllProduction(): Promise<void>;
    clearAttendanceByMonth(month: string): Promise<void>;
    clearInventoryTransactions(): Promise<void>;
    clearProductionByMonth(month: string): Promise<void>;
    createEmployee(name: string, mobile: string, joiningDate: string, workerType: string, accountNumber: string, ifscCode: string, bankName: string): Promise<Employee>;
    createInventoryItem(name: string, quantity: bigint, unit: string, itemType: string, pricePerUnit: number): Promise<InventoryItem>;
    createOperation(name: string, ratePerPiece: number): Promise<Operation>;
    deleteEmployee(id: string): Promise<boolean>;
    deleteInventoryItem(id: string): Promise<boolean>;
    deleteOperation(id: string): Promise<boolean>;
    getAttendanceByDate(date: string): Promise<Array<Attendance>>;
    getAttendanceByEmployeeMonth(employeeId: string, month: string): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDataCounts(): Promise<Counts>;
    getEmployee(id: string): Promise<Employee | null>;
    getInventoryStats(): Promise<InventoryStats>;
    getMonthlySalarySheet(month: string): Promise<Array<SalaryRecord>>;
    getOperation(id: string): Promise<Operation | null>;
    getProductionByDate(date: string): Promise<Array<ProductionEntry>>;
    getProductionByEmployee(employeeId: string): Promise<Array<ProductionEntry>>;
    getProductionByEmployeeMonth(employeeId: string, month: string): Promise<Array<ProductionEntry>>;
    getProductionByMonth(month: string): Promise<Array<ProductionEntry>>;
    getStockTransactionsByItem(itemId: string): Promise<Array<StockTransaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listEmployees(): Promise<Array<Employee>>;
    listInventoryItems(): Promise<Array<InventoryItem>>;
    listOperations(): Promise<Array<Operation>>;
    markAttendance(date: string, employeeId: string, status: string): Promise<Attendance>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEmployees(q: string): Promise<Array<Employee>>;
    searchOperations(q: string): Promise<Array<Operation>>;
    startsWith(t: string, prefix: string): Promise<boolean>;
    updateEmployee(id: string, name: string, mobile: string, joiningDate: string, workerType: string, accountNumber: string, ifscCode: string, bankName: string, status: string): Promise<Employee | null>;
    updateInventoryItem(id: string, name: string, quantity: bigint, unit: string, itemType: string, currentQuantity: bigint, pricePerUnit: number): Promise<InventoryItem | null>;
    updateOperation(id: string, name: string, ratePerPiece: number): Promise<Operation | null>;
}
import type { Employee as _Employee, InventoryItem as _InventoryItem, Operation as _Operation, ProductionEntry as _ProductionEntry, StockTransaction as _StockTransaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProductionEntry(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<ProductionEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionEntry(arg0, arg1, arg2, arg3);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionEntry(arg0, arg1, arg2, arg3);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStockTransaction(arg0: string, arg1: string, arg2: bigint, arg3: number, arg4: string, arg5: string, arg6: string): Promise<StockTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addStockTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStockTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearAllAttendance(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllAttendance();
            return result;
        }
    }
    async clearAllEmployees(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllEmployees();
            return result;
        }
    }
    async clearAllInventory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllInventory();
            return result;
        }
    }
    async clearAllOperations(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllOperations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllOperations();
            return result;
        }
    }
    async clearAllProduction(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllProduction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllProduction();
            return result;
        }
    }
    async clearAttendanceByMonth(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAttendanceByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAttendanceByMonth(arg0);
            return result;
        }
    }
    async clearInventoryTransactions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearInventoryTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearInventoryTransactions();
            return result;
        }
    }
    async clearProductionByMonth(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearProductionByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearProductionByMonth(arg0);
            return result;
        }
    }
    async createEmployee(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createInventoryItem(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: number): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createOperation(arg0: string, arg1: number): Promise<Operation> {
        if (this.processError) {
            try {
                const result = await this.actor.createOperation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOperation(arg0, arg1);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteOperation(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOperation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOperation(arg0);
            return result;
        }
    }
    async getAttendanceByDate(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0);
            return result;
        }
    }
    async getAttendanceByEmployeeMonth(arg0: string, arg1: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByEmployeeMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByEmployeeMonth(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDataCounts(): Promise<Counts> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataCounts();
            return result;
        }
    }
    async getEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryStats(): Promise<InventoryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryStats();
            return result;
        }
    }
    async getMonthlySalarySheet(arg0: string): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySalarySheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySalarySheet(arg0);
            return result;
        }
    }
    async getOperation(arg0: string): Promise<Operation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOperation(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOperation(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionByDate(arg0: string): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionByDate(arg0);
            return result;
        }
    }
    async getProductionByEmployee(arg0: string): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionByEmployee(arg0);
            return result;
        }
    }
    async getProductionByEmployeeMonth(arg0: string, arg1: string): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionByEmployeeMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionByEmployeeMonth(arg0, arg1);
            return result;
        }
    }
    async getProductionByMonth(arg0: string): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionByMonth(arg0);
            return result;
        }
    }
    async getStockTransactionsByItem(arg0: string): Promise<Array<StockTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockTransactionsByItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockTransactionsByItem(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees();
            return result;
        }
    }
    async listInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventoryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventoryItems();
            return result;
        }
    }
    async listOperations(): Promise<Array<Operation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOperations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOperations();
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: string, arg2: string): Promise<Attendance> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchEmployees(arg0: string): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEmployees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEmployees(arg0);
            return result;
        }
    }
    async searchOperations(arg0: string): Promise<Array<Operation>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchOperations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchOperations(arg0);
            return result;
        }
    }
    async startsWith(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startsWith(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startsWith(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventoryItem(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: bigint, arg6: number): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOperation(arg0: string, arg1: string, arg2: number): Promise<Operation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOperation(arg0, arg1, arg2);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOperation(arg0, arg1, arg2);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductionEntry]): ProductionEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StockTransaction]): StockTransaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Operation]): Operation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
